[package]
name = "audio_compare_lib"
version = "0.1.0"
edition = "2021"
description = "A Rust library for comparing wav audio files."
repository = "https://github.com/vffuunnyy/audio_compare_lib"
license = "MIT"

[dependencies]
hound = "3.5.1"
rustfft = "6.2.0"
